defaults:
  - _self_
  - workspace_config
  - agent: td3
  - override hydra/launcher: submitit_slurm

hydra:
  job:
    chdir: True
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${agent.name}_${task}
  sweep:
    dir: ./exp_sweep/${now:%Y.%m.%d}_${task}/${now:%H%M%S}_${agent.name}_${task}
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 4300
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 400
    nodes: 1
    submitit_folder: ./exp_sweep/${now:%Y.%m.%d}_${task}/${now:%H%M%S}_${agent.name}_${task}/.slurm
    partition: learnlab # devlab learnlab